---
default_crio_packages:
  - "cri-o=1.19.0~0"
  - "cri-o-runc=1.0.0-6"

crio_packages: "{{ ubuntu_crio_packages | default(default_crio_packages) }}"

crio_runc_path: /usr/sbin/runc

crio_kubernetes_version_matrix:
  "1.18": "1.17"
  "1.17": "1.17"
  "1.16": "1.16"
